### ISSUE TITLE
ルール説明画面を表題と説明を体系化する

### ISSUE THREAD

**Issue by k-hayashi-dott** [yousukeend/alpinea#37]
「ルール説明」は表題
説明文は説明文。

**Comment by yousukeend** [comment]
## Checklist for Developer

- [x] 最新のdevelopブランチをPullした。 Pulled the latest develop branch.
- [x] Pull RequestをIssueに紐付けた。 Connected with the issue.
- [x] 自分をAssignした。Assigned yourself.
- [x] レビュワーを指定した。Assigned reviewer.

## そのほかの関連するIssue / Related issues other than connected one

- #37

## 変更内容 / Details of Changes
1. 説明画面でルール説明のフォントと説明文のフォントが区別つくように変更しました。

## スクリーンショット / Screenshots

<img width="838" alt="スクリーンショット 2023-08-28 15 24 58" src="https://github.com/yousukeend/alpinea/assets/40225496/806f0133-66d9-4aed-9c13-848deed8bebe">

## レビューするポイント/ Points for review
- `localhost:4200/info`説明画面で、上記のスクショのように表示される
