### ISSUE TITLE
クイズ画面のモックアップを作成する
スマホ版とWeb版を一緒に並行する

### ISSUE THREAD

**Issue by yousukeend** [yousukeend/alpinea#5]
## 概要 (Summary):
問題文、動画 (リロードボタン含む)/ 画像の枠、選択肢を作成する

問題文は card Material
https://material.angular.io/components/card/overview

動画 / 画像は card Material

選択肢 Button
https://material.angular.io/components/button/overview
## 誰が使うか (For whom):
ユーザー
## 何のために or どのように実装するか (For what):
クイズアプリを作るため

Angular Materialの card、Buttonを使ってデザインを整える。
## 達成目標:
クイズ画面のデザインが完成すること

**Comment by abe127** [comment]
動画はDriveからiframeとかvideo使って表示する
https://dottio.slack.com/archives/C1Y3C5EHY/p1686643196699479?thread_ts=1686639653.069059&cid=C1Y3C5EHY
https://www.geboku-kyoudai.com/entry/GoogleDrive-mp4
