### ISSUE TITLE
クイズ画面に問題、動画 / 写真、選択肢を表示する

### ISSUE THREAD

**Issue by yousukeend** [yousukeend/alpinea#8]
## 概要 (Summary):
クイズ画面に問題文、動画 / 写真、選択肢が表示されるようにする
## 誰が使うか (For whom):
ユーザー
## 何のために or どのように実装するか (For what):
クイズ内容をユーザーに表示させるため
YouTubeのプレイヤーを使用する
https://developers.google.com/youtube/player_parameters?hl=ja
## 達成目標:
クイズ内容が表示されること

**Comment by abe127** [comment]
- それぞれの動画のiframe の共有リンクを取っておいて、
- 問題番号と共有リンクの対比をするJSON構造とかを作って
- 問題に対応したリンクを埋め込めば良いと思います

https://dottio.slack.com/archives/C1Y3C5EHY/p1686643350757459?thread_ts=1686639653.069059&cid=C1Y3C5EHY

**Comment by k-hayashi-dott** [comment]
- 説明画面でスタートボタンを押したときの画面遷移はこのIssueで対応する
- 問題をコード上にどうやって持っておくか？をまずは設計する
